### ISSUE TITLE
Wrong theme uploading functionality

### ISSUE THREAD

**Issue by t13ka** [VirtoCommerce/vc-module-content#36] opened 2019-11-14 09:22 UTC
> when I create a new theme under "Content/Electronics" called test and then select that theme on the "themes list" blade,  then dismiss "manage theme assets" blade and then click upload on "themes list" blade while new theme "test" is selected, upload of .zip appears to work, but nothing ends up under the Electronics\test2 directory.  The theme is not unzipped and not placed anywhere, it is just "gone".   If I try to upload it on the "theme assets" blade, the zip is uploaded, but the contents are not unzipped there either, the file just sits there.  
Also , theme uploading by .zip still does not work.

If we open the attached zip we can see the root folder "default". The new folder in UI creates in accordance with the name of this root folder. It looks like the client already has a folder with the name "Default" and tries to upload zip file over the wrong folder (Test) and surely all content from the zip is unzipping(and overwrites) in default to the "default" folder. This leads to this behavior.

**Comment by woody0130** [comment] 2019-11-15 03:27
Note that when building the theme from the "natrol-theme" project (a copy of vc-theme supplied by Virto)  The zip file is built with "default" being the root of the theme...

**Comment by trueboroda** [comment] 2020-01-13 08:38
The uploaded theme has the same name as archive. Behavior that was described was wrong and was caused by error that is fixed now and will be released soon. https://github.com/VirtoCommerce/vc-platform/pull/1765

**Comment by yecli** [comment] 2020-01-15 14:27
Released in https://github.com/VirtoCommerce/vc-module-content/releases/tag/v2.13.12

**Closed by yecli** 2020-01-15 14:27 UTC
